get_env: keep TEMP variable, as it is used by the IRKernel
R uses the TEMP variable to create a sandbox. If the TEMP variable is
not defined, the IRKernel fails on startup with:

Fatal error: creation of tmpfile failed -- set TMPDIR suitably?

Signed-off-by: Alejandro Del Castillo <alejandro.delcastillo@ni.com>